language: cpp

compiler:
- gcc

sudo: required

before_install:
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo -E apt-get update
- sudo apt-get install libsdl2-2.0-0
- wget https://www.libsdl.org/release/SDL2-2.0.12.tar.gz -O SDL2-2.0.12.tar.gz
- tar -xzvf SDL2-2.0.12.tar.gz

install:
- sudo apt-get install -qq g++-9
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-9 90
- cd SDL2-2.0.12
- 'if [ ! -d "./build" ];
 then mkdir build;
fi'
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Debug
- make && sudo make install

script:

#task 1 01-hello
- cd ../../01-hello
- 'if [ ! -d "./build" ];
 then mkdir build;
fi'
- cd build
- cmake ..
- make 01-hello-static
- ./bin/01-hello-static
- make 01-hello-shared
- ./bin/01-hello-shared

#task 2 02-sdl
- cd ../../02-sdl
- 'if [ ! -d "./build" ];
 then mkdir build;
fi'
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Debug
- make 
- ./02-sdl-shared/02-sdl-shared
- ./02-sdl-static/02-sdl-static

#task 3 03-game-loop
- cd ../../03-game-loop
- 'if [ ! -d "./build" ];
 then mkdir build;
fi'
- cd build
- cmake .. -DCMAKE_BUILD_TYPE=Debug
- make 
- ./src/03-game-loop-shared


