language: cpp

compiler:
- gcc

sudo: required

before_install:
# C++14
- sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
- sudo apt-get update -qq
- sudo -E add-apt-repository -y ppa:george-edison55/cmake-3.x
- sudo -E apt-get update
install:
# C++14
- sudo apt-get install -qq g++-6
- sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-6 90
- sudo apt-get install cmake
- cmake --version
script:

#task 1 01_hello_static
- cd 01_hello/01_hello_static
- 'if [ ! -d "./build" ];
 then mkdir build;
fi'
- cd build
- cmake ..
- make
- ./source/01_hello_static
  
#task 1 01_hello_dynamic
- cd ../../../01_hello/01_hello_dynamic
- 'if [ ! -d "./build" ];
 then mkdir build;
fi'
- cd build
- cmake ..
- make
- ./source/01_hello_dynamic
