- sudo apt-get install libsdl2-2.0.12
- wget https://www.libsdl.org/release/SDL2-2.0.12.tar.gz -O SDL2-2.0.12.tar.gz
- tar -xzvf SDL2-2.0.12.tar.gz


- "(cd SDL2-2.0.12 && ./configure && make && sudo make install)"
